---
apiVersion: build.knative.dev/v1alpha1
kind: BuildTemplate
metadata:
  name: cnb
spec:
  parameters:
  - name: IMAGE
    description: The image you wish to create. For example, "repo/example", or "example.com/repo/image".
  - name: RUN_IMAGE
    description: The run image buildpacks will use as the base for IMAGE.
    default: packs/run
  - name: USE_CRED_HELPERS
    description: Use Docker credential helpers for Google's GCR, Amazon's ECR, or Microsoft's ACR.
    default: 'true'

  steps:
  - name: prepare
    image: packs/base
    command: ["bash"]
    # FIXME: Apps with a top-level `app` folder don't work.
    # Maybe we should create `/lifecycle/knative` to handle this step (and maybe other steps)?
    args: ["-c", "mkdir /workspace/app && shopt -s extglob dotglob && mv /workspace/!(app) /workspace/app/ && chown -R pack:pack /workspace /builder/home"]
  - name: detect
    image: packs/build
    command: ["/lifecycle/detector"]
    imagePullPolicy: Always
  - name: analyze
    image: packs/util
    command: ["/lifecycle/analyzer"]
    args: ["${IMAGE}"]
    env:
    - name: PACK_USE_HELPERS
      value: ${USE_CRED_HELPERS}
    imagePullPolicy: Always
  - name: build
    image: packs/build
    volumeMounts:
    - name: cache
      mountPath: /cache
    imagePullPolicy: Always
  - name: export
    image: packs/util
    command: ["/lifecycle/exporter"]
    args: ["${IMAGE}"]
    env:
    - name: PACK_RUN_IMAGE
      value: ${RUN_IMAGE}
    - name: PACK_USE_HELPERS
      value: ${USE_CRED_HELPERS}
    imagePullPolicy: Always

  volumes:
  - name: cache
    emptyDir: {}
